api_platform:
    title: 'API oTrak'
    version: '0.1.0'
    show_webby: false

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header

    collection:
        pagination:
            enabled: false

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
