api_platform:
    title: 'API oTrak'
    version: '0.0.1'
    show_webby: false

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
